version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis

  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - 5432:5432
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sagar@example.com
      PGADMIN_DEFAULT_PASSWORD: sagar
      # PGADMIN_DEFAULT_PORT: 80
    ports:
      - 5050:80
    networks:
      app_net:
        ipv4_address: 192.168.0.3

  backend:
    build:
      context: ./backend
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
      # celery:
      #   restart: always
      #   container_name: celery
      #   build:
      #     context: ./backend
      #   command: celery -A config worker -l DEBUG
      #   volumes:
      #     - .:/django
      #   depends_on:
      # - db
      #     - redis
      #     - backend

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx_setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  react_build:


networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
