import { fuseReactLatestVersion } from './atom/changelog/ChangelogDoc';
// import FuseComponentsNavigation from './fuse-components/FuseComponentsNavigation';
// import MaterialUIComponentsNavigation from './material-ui-components/MaterialUIComponentsNavigation';
// import ThirdPartyComponentsNavigation from './third-party-components/ThirdPartyComponentsNavigation';
import { authRoles } from 'src/app/auth';

const DocumentationNavigation = {
  id: 'documentation',
  title: 'Documentation',
  type: 'group',
  icon: 'books',
  children: [
    {
      id: 'atom_frontend',
      title: 'Atom',
      type: 'collapse',
      icon: 'play_arrow',

      children: [
        {
          id: 'changelog',
          title: 'Changelog',
          type: 'item',
          icon: 'history',
          url: '/documentation/atom/changelog',
          badge: {
            title: fuseReactLatestVersion,
            bg: 'rgb(236, 12, 142)',
            fg: '#FFFFFF',
          },
        },
        {
          id: 'getting-started',
          title: 'Getting Started',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'introduction-doc',
              title: 'Introduction',
              type: 'item',
              url: '/documentation/atom/getting-started/introduction',
            },
            {
              id: 'login-doc',
              title: 'Login',
              type: 'item',
              url: '/documentation/atom/getting-started/login',
            },
            {
              id: 'notification-doc',
              title: 'Notification',
              type: 'item',
              url: '/documentation/atom/getting-started/notification',
            },
            {
              id: 'logout-doc',
              title: 'Logout',
              type: 'item',
              url: '/documentation/atom/getting-started/logout',
            },
          ],
        },
        {
          id: 'mytask',
          title: 'My Task',
          type: 'item',
          url: '/documentation/atom/mytask',
        },
        {
          id: 'users',
          title: 'Users',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'contact-doc',
              title: 'Contact',
              type: 'item',
              url: '/documentation/atom/users/contact',
            },
            {
              id: 'group-doc',
              title: 'Group',
              type: 'item',
              url: '/documentation/atom/users/group',
            },
            {
              id: 'permision-doc',
              title: 'Permision',
              type: 'item',
              url: '/documentation/atom/users/permision',
            },
          ],
        },
        {
          id: 'entities',
          title: 'Projects',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'overview-doc',
              title: 'Overview',
              type: 'item',
              url: '/documentation/atom/entities/overview',
            },
            {
              id: 'task_assignment-doc',
              title: 'Task-Assignment',
              type: 'item',
              url: '/documentation/atom/entities/task_assignment',
            },
            {
              id: 'project-doc',
              title: 'Project',
              type: 'item',
              url: '/documentation/atom/entities/project',
            },
            {
              id: 'asset-doc',
              title: 'Asset',
              type: 'item',
              url: '/documentation/atom/entities/asset',
            },
            {
              id: 'episode-doc',
              title: 'Episode',
              type: 'item',
              url: '/documentation/atom/entities/episode',
            },
            {
              id: 'sequence-doc',
              title: 'Sequence',
              type: 'item',
              url: '/documentation/atom/entities/sequence',
            },
            {
              id: 'shot-doc',
              title: 'Shot',
              type: 'item',
              url: '/documentation/atom/entities/shot',
            },
            {
              id: 'step-doc',
              title: 'Step',
              type: 'item',
              url: '/documentation/atom/entities/step',
            },
            {
              id: 'task-doc',
              title: 'Task',
              type: 'item',
              url: '/documentation/atom/entities/task',
            },
            {
              id: 'version-doc',
              title: 'Version',
              type: 'item',
              url: '/documentation/atom/entities/version',
            },
            {
              id: 'notes-doc',
              title: 'Notes',
              type: 'item',
              url: '/documentation/atom/entities/notes',
            },
          ],
        },
        {
          id: 'utilities',
          title: 'Utilities',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'role-doc',
              title: 'Role',
              type: 'item',
              url: '/documentation/atom/utilities/role',
            },
            {
              id: 'status-doc',
              title: 'Status',
              type: 'item',
              url: '/documentation/atom/utilities/status',
            },
            {
              id: 'step-doc',
              title: 'Step',
              type: 'item',
              url: '/documentation/atom/utilities/step',
            },
            {
              id: 'priority-doc',
              title: 'Priority',
              type: 'item',
              url: '/documentation/atom/utilities/priority',
            },
            {
              id: 'tool-doc',
              title: 'Tool',
              type: 'item',
              url: '/documentation/atom/utilities/tool',
            },
          ],
        },
        {
          id: 'settings',
          title: 'Settings',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'email-doc',
              title: 'Email',
              type: 'item',
              url: '/documentation/atom/settings/email',
            },
          ],
        },
        {
          id: 'review',
          title: 'Review',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'internal-doc',
              title: 'Internal',
              type: 'item',
              url: '/documentation/atom/review/internal',
            },
            {
              id: 'client-doc',
              title: 'Client',
              type: 'item',
              url: '/documentation/atom/review/client',
            },
          ],
        },
      ],
    },

    {
      id: 'python_api',
      title: 'Python API',
      type: 'collapse',
      icon: 'dashboard',
      auth: authRoles.developer,
      children: [
        {
          id: 'RestGetting-Start',
          title: 'Getting Started',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'RestIntro-Doc',
              title: 'Introduction',
              type: 'item',
              url: '/documentation/python_api/getting-started/introduction',
            },
          ],
        },
        {
          id: 'RestAccountsDoc',
          title: 'Accounts',
          type: 'collapse',
          icon: 'lock',
          children: [
            {
              id: 'RestUsersDoc',
              title: 'Users',
              type: 'item',
              icon: 'person_add',
              url: '/documentation/python_api/accounts/users',
            },
            {
              id: 'RestGroupsDoc',
              title: 'Groups',
              type: 'item',
              icon: 'groups',
              url: '/documentation/python_api/accounts/groups',
            },
          ],
        },
        {
          id: 'RestEntitiesDoc',
          title: 'Entities',
          type: 'collapse',
          icon: 'folder',
          children: [
            {
              id: 'RestAssetsDoc',
              title: 'Assets',
              type: 'item',
              icon: 'view_quilt',
              url: '/documentation/python_api/entities/asset',
            },
            {
              id: 'RestEpisodeDoc',
              title: 'Episode',
              type: 'item',
              icon: 'developer_board',
              url: '/documentation/python_api/entities/episode',
            },
            {
              id: 'RestNotesDoc',
              title: 'Notes',
              type: 'item',
              icon: 'note',
              url: '/documentation/python_api/entities/notes',
            },
            {
              id: 'RestProjectDoc',
              title: 'Project',
              type: 'item',
              icon: 'widgets',
              url: '/documentation/python_api/entities/project',
            },
            {
              id: 'RestSequenceDoc',
              title: 'Sequence',
              type: 'item',
              icon: 'receipt',
              url: '/documentation/python_api/entities/sequence',
            },
            {
              id: 'RestShotDoc',
              title: 'Shot',
              type: 'item',
              icon: 'layers',
              url: '/documentation/python_api/entities/shot',
            },
            {
              id: 'RestStepDoc',
              title: 'Step',
              type: 'item',
              icon: 'settings_input_component',
              url: '/documentation/python_api/entities/step',
            },
            {
              id: 'RestTaskDoc',
              title: 'Task',
              type: 'item',
              icon: 'verified_user',
              url: '/documentation/python_api/entities/task',
            },
            {
              id: 'RestVersionDoc',
              title: 'Version',
              type: 'item',
              icon: 'list',
              url: '/documentation/python_api/entities/version',
            },
          ],
        },
        {
          id: 'RestUploadFileDoc',
          title: 'Upload Files',
          type: 'group',
          icon: 'upload',
          url: '/documentation/python_api/upload',
        },
        {
          id: 'RestUserTaskDoc',
          title: 'User Task',
          type: 'group',
          icon: 'history',
          url: '/documentation/python_api/userTask',
        },
        {
          id: 'RestUtilitiesDoc',
          title: 'Utilities',
          type: 'collapse',
          icon: 'bookmarks',
          children: [
            {
              id: 'RestPriorityDoc',
              title: 'Priority',
              type: 'item',
              icon: 'import_contacts',
              url: '/documentation/python_api/utilities/priority',
            },
            {
              id: 'RestRoleDoc',
              title: 'Role',
              type: 'item',
              icon: 'security',
              url: '/documentation/python_api/utilities/role',
            },
            {
              id: 'RestStatusDoc',
              title: 'Status',
              type: 'item',
              icon: 'note',
              url: '/documentation/python_api/utilities/status',
            },
            {
              id: 'RestStepDoc',
              title: 'Step',
              type: 'item',
              icon: 'link',
              url: '/documentation/python_api/utilities/step',
            },
            {
              id: 'RestToolDoc',
              title: 'Tool',
              type: 'item',
              icon: 'build',
              url: '/documentation/python_api/utilities/tool',
            },
          ],
        },
      ],
    },

    {
      id: 'rest_api',
      title: 'Rest API',
      type: 'collapse',
      icon: 'dashboard',
      auth: authRoles.developer,
      children: [
        {
          id: 'BackGetting-Started',
          title: 'Getting Started',
          type: 'collapse',
          icon: 'play_arrow',
          children: [
            {
              id: 'BackIntroduction-Doc',
              title: 'Introduction',
              type: 'item',
              url: '/documentation/rest_api/getting-started/introduction',
            },
            {
              id: 'BackLogin-Doc',
              title: 'Login',
              type: 'item',
              url: '/documentation/rest_api/getting-started/login',
            },
          ],
        },
        {
          id: 'BackAccountsDoc',
          title: 'Accounts',
          type: 'collapse',
          icon: 'lock',
          children: [
            {
              id: 'BackUsersDoc',
              title: 'Users',
              type: 'item',
              icon: 'person_add',
              url: '/documentation/rest_api/accountsBack/users',
            },
            {
              id: 'BackGroupsDoc',
              title: 'Groups',
              type: 'item',
              icon: 'groups',
              url: '/documentation/rest_api/accountsBack/groups',
            },
          ],
        },
        {
          id: 'BackEntitiesDoc',
          title: 'Entities',
          type: 'collapse',
          icon: 'folder',
          children: [
            {
              id: 'BackAssetsDoc',
              title: 'Assets',
              type: 'item',
              icon: 'view_quilt',
              url: '/documentation/rest_api/entitiesBack/asset',
            },
            {
              id: 'BackEpisodeDoc',
              title: 'Episode',
              type: 'item',
              icon: 'developer_board',
              url: '/documentation/rest_api/entitiesBack/episode',
            },
            {
              id: 'BackNotesDoc',
              title: 'Notes',
              type: 'item',
              icon: 'note',
              url: '/documentation/rest_api/entitiesBack/notes',
            },
            {
              id: 'BackProjectDoc',
              title: 'Project',
              type: 'item',
              icon: 'widgets',
              url: '/documentation/rest_api/entitiesBack/project',
            },
            {
              id: 'BackSequenceDoc',
              title: 'Sequence',
              type: 'item',
              icon: 'receipt',
              url: '/documentation/rest_api/entitiesBack/sequence',
            },
            {
              id: 'BackShotDoc',
              title: 'Shot',
              type: 'item',
              icon: 'layers',
              url: '/documentation/rest_api/entitiesBack/shot',
            },
            {
              id: 'BackStepDoc',
              title: 'Step',
              type: 'item',
              icon: 'settings_input_component',
              url: '/documentation/rest_api/entitiesBack/step',
            },
            {
              id: 'BackTaskDoc',
              title: 'Task',
              type: 'item',
              icon: 'verified_user',
              url: '/documentation/rest_api/entitiesBack/task',
            },
            {
              id: 'BackVersionDoc',
              title: 'Version',
              type: 'item',
              icon: 'list',
              url: '/documentation/rest_api/entitiesBack/version',
            },
          ],
        },
        {
          id: 'BackUploadFileDoc',
          title: 'Upload Files',
          type: 'group',
          icon: 'upload',
          url: '/documentation/rest_api/uploadBack',
        },
        {
          id: 'BackUserTaskDoc',
          title: 'User Task',
          type: 'group',
          icon: 'history',
          url: '/documentation/rest_api/userTaskBack',
        },
        {
          id: 'BackUtilitiesDoc',
          title: 'Utilities',
          type: 'collapse',
          icon: 'bookmarks',
          children: [
            {
              id: 'BackPriorityDoc',
              title: 'Priority',
              type: 'item',
              icon: 'import_contacts',
              url: '/documentation/rest_api/utilitiesBack/priority',
            },
            {
              id: 'BackRoleDoc',
              title: 'Role',
              type: 'item',
              icon: 'security',
              url: '/documentation/rest_api/utilitiesBack/role',
            },
            {
              id: 'BackStatusDoc',
              title: 'Status',
              type: 'item',
              icon: 'note',
              url: '/documentation/rest_api/utilitiesBack/status',
            },
            {
              id: 'BackStepDoc',
              title: 'Step',
              type: 'item',
              icon: 'link',
              url: '/documentation/rest_api/utilitiesBack/step',
            },
            {
              id: 'BackToolDoc',
              title: 'Tool',
              type: 'item',
              icon: 'build',
              url: '/documentation/rest_api/utilitiesBack/tool',
            },
          ],
        },
      ],
    },
  ],
};

export default DocumentationNavigation;
